info:
  profile: default
  name: greeting131
  spring:
    application:
      name: greeting
    cloud:
      consul:
        host: localhost
        port: 8500
detail:
  profile: default
  name: greeting12
