server:
  port: 8088

copyright : Mr.Gao883385566666111111

spring:
  application:
    name: timing
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      config:
        enabled: true
      discovery:
        enabled: true
#        instanceId: now-1
        serviceName: now1
#        hostname: localhost
#        port: 8080
        
  zipkin:
    baseUrl: http://localhost:6060

  
